import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { HomePage } from "@/src/components/events/events-page";
import { Footer } from "@/src/components/footer/footer";
import { Header } from "@/src/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export default function Home({data}:{data:any}) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <HomePage data={data}/>
      
    </>
  );
}
export async function getServerSideProps(){
  const {events_categories}= await import('../data/data.json')
  // const res=await fetch('URL')
  // const data1=await res.json()
  return {
    props:{
      data:events_categories
    }
  }
}
